/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IRewarderInterface extends ethers.utils.Interface {
  functions: {
    "onJoeReward(address,uint256)": FunctionFragment;
    "pendingTokens(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "onJoeReward",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "pendingTokens",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "onJoeReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingTokens",
    data: BytesLike
  ): Result;

  events: {};
}

export class IRewarder extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IRewarderInterface;

  functions: {
    onJoeReward(
      user: string,
      newLpAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "onJoeReward(address,uint256)"(
      user: string,
      newLpAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    pendingTokens(
      user: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { pending: BigNumber }>;

    "pendingTokens(address)"(
      user: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { pending: BigNumber }>;
  };

  onJoeReward(
    user: string,
    newLpAmount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "onJoeReward(address,uint256)"(
    user: string,
    newLpAmount: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  pendingTokens(user: string, overrides?: CallOverrides): Promise<BigNumber>;

  "pendingTokens(address)"(
    user: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    onJoeReward(
      user: string,
      newLpAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "onJoeReward(address,uint256)"(
      user: string,
      newLpAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    pendingTokens(user: string, overrides?: CallOverrides): Promise<BigNumber>;

    "pendingTokens(address)"(
      user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    onJoeReward(
      user: string,
      newLpAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "onJoeReward(address,uint256)"(
      user: string,
      newLpAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    pendingTokens(user: string, overrides?: CallOverrides): Promise<BigNumber>;

    "pendingTokens(address)"(
      user: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    onJoeReward(
      user: string,
      newLpAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "onJoeReward(address,uint256)"(
      user: string,
      newLpAmount: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    pendingTokens(
      user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "pendingTokens(address)"(
      user: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
